name: 'Clarity & Contempt'
favicon: null
layout_spectrum: 0.8172824736684561
typography_spectrum: 0.59416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.06172217335551977
  saturation: 0.024376342073082924
  rhythmicContrast: 0.37719648610800505
purpose: []
